---
version: '3.1'

services:
  app:
    build: .
    environment:
      - FLASK_APP=index.py
    env_file:
      - .env
    command:
      - flask
      - run
      - --host=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - .:/app
    - ./tmp/nginx/log:/var/log/nginx
    - ./tmp/nginx/cache:/etc/nginx/cache
    ports:
    - 8080:80
